### PR TITLE
Added seed in PlanckAquisition

### PR DESCRIPTION
**Pull request by NicolettaK**
Default value is seed=None: in this case it generates a random seed to
compute Planck noise.
If seed is a number then it is used to generate the noise.

### CODE REVIEW

**Comment by pchanial** [comment]
Great ! Just a couple of nitpicking remarks.

1) Could you add the keyword 'comm' to the PlanckAcquisition to give more flexibility on parallelization, and add this check for the seed?

```python
def __init__(self, ..., comm=None):
    """
    comm : mpi4py.MPI.Comm
        The acquisition's MPI communicator.
    """
    ...
    if comm is None:
        comm = MPI.COMM_WORLD
    self.comm = comm

    if seed is not None and seed != comm.bcast(seed, root=0):
        raise ValueError('The specified seed is not the same on all the nodes.')
```

2) You've unintentionally added a blank line before the method get_observation.

3) The way you've written won't quite work since randint(low=0) always returns 0. Setting a higher value won't help: since the random state is restored every time you call get_noise, by repeatingly calling it, you would get the same realization. It can be refactored like that (no need to capitalize SIMULATED_PLANCK_SEED, use 'is' instead of '==' when checking for None):

```python
def get_noise(self):
    state = np.random.get_state()
    if self.seed is None:
        np.random.set_state(comm.bcast(state, root=0))
    else:
        np.random.seed(self.seed)
    out = np.random.standard_normal(self._true_sky.shape) * self.sigma
    if self.seed is not None or self.comm.rank != 0:
        np.random.set_state(state)
    return out
```

**Comment by NicolettaK** [comment]
Thanks!
I have now implemented the changes that you suggest in the new commit.

**Comment by pchanial** [comment]
Could you please rebase your repository to simplify the history? I've explained how to do it on the wiki' github page.

**Comment by pchanial** [comment]
OK, just two more things: a useless import and the commit message is repeated four times.

Could  you please remove the change:

    -from pysimulators import Acquisition, FitsArray
    +from pysimulators import Acquisition, FitsArray, ProjectionOperator

This import is not used anymore. To do so:
remove ", ProjectionOperator"

    $ git commit qubic/acquisition.py -m "cont"

and squash the two commits into one:

    $ git rebase -i HEAD~2

In the first line, replace 'pick' with 'reword' and in the second line 'pick' with 'squash'.
Save, an editor will pop-up to let you amend the commit message.

Once it is done:

$ git push -f

And ask JC to merge the pull request. I'll be away the whole week.

**Pull request closed without merging**
